// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyFont(arg1:string):Promise<void>;

export function GetFonts():Promise<Array<string>>;

export function GetStatus():Promise<main.Status>;

export function ResetFont():Promise<void>;
