// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyFont(arg1) {
  return window['go']['main']['App']['ApplyFont'](arg1);
}

export function GetFonts() {
  return window['go']['main']['App']['GetFonts']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ResetFont() {
  return window['go']['main']['App']['ResetFont']();
}
